# From: https://about.gitlab.com/2017/09/21/how-to-create-ci-cd-pipeline-with-autodeploy-to-kubernetes-using-gitlab-and-helm/

variables:
  REPO_DIR: gitlab.com/elixxir
  REPO_NAME: xx-messenger-reports
  DOCKER_IMAGE: elixxirlabs/cuda-go:go1.16-cuda11.1
  MIN_CODE_COVERAGE: "0.0"

before_script:
  ##
  ## Go Setup
  ##
  - go version || echo "Go executable not found."
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - echo $PWD
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa $GITLAB_SERVER > ~/.ssh/known_hosts
  - git config --global url."git@$GITLAB_SERVER:".insteadOf "https://gitlab.com/"
  - git config --global url."git@$GITLAB_SERVER:".insteadOf "https://git.xx.network/"
  - export PATH=$HOME/go/bin:$PATH

stages:
  - build

build:
  stage: build
  image: $DOCKER_IMAGE
  script:
    - git clean -ffdx
    - go mod vendor -v
    # - go build ./...
    - go mod tidy
    #- mkdir -p testdata

    # Test coverage
    #- go-acc --covermode atomic --output testdata/coverage.out ./... -- -v
    # Exclude some specific packages and files
    #- grep -v -e cmd testdata/coverage.out > testdata/coverage-real.out
    #- go tool cover -func=testdata/coverage-real.out
    #- go tool cover -html=testdata/coverage-real.out -o testdata/coverage.html

    # Test Coverage Check
    #- go tool cover -func=testdata/coverage-real.out | grep "total:" | awk '{print $3}' | sed 's/\%//g' > testdata/coverage-percentage.txt
    #- export CODE_CHECK=$(echo "$(cat testdata/coverage-percentage.txt) >= $MIN_CODE_COVERAGE" | bc -l)
    #- (if [ "$CODE_CHECK" == "1" ]; then echo "Minimum coverage of $MIN_CODE_COVERAGE succeeded"; else echo "Minimum coverage of $MIN_CODE_COVERAGE failed"; exit 1; fi);

    - mkdir -p release
    - mkdir -p release/client
    - GOOS=linux GOARCH=amd64 go build -o release/reports.linux64 main.go
    - GOOS=darwin GOARCH=amd64 go build -o release/reports.darwin64 main.go
    - GOOS=windows GOARCH=amd64 go build -o release/reports.windows main.go
    #- GOOS=js GOARCH=wasm go build -o release/main.wasm
  artifacts:
    paths:
      - vendor/
      #- testdata/
      - release/
